### ISSUE TITLE
stateListAnimator not working

### ISSUE THREAD

**Issue by THEMrFill** [nvl2val/CardView#1]
I've been using the Android CardView and have a "press" animation in a state list animator, and trying to convert to this version to be able to change the shadow (so that it matches the color scheme of the app), but state lists aren't working.

My `press_on_touch.xml` looks like this:
`<?xml version="1.0" **encoding="utf-8"?>`
`<!-- animate the translationZ property of a view when pressed -->`
`<selector xmlns:android="http://schemas.android.com/apk/res/android">`
`    <item`
`        android:state_enabled="true"`
`        android:state_pressed="true">`
`        <set>`
`            <objectAnimator`
`                android:duration="100"`
`                android:propertyName="translationZ"`
`                android:valueTo="0dp"`
`                android:valueType="floatType"/>`
`        </set>`
`    </item>`
`    <item>`
`        <set>`
`            <objectAnimator`
`                android:duration="100"`
`                android:propertyName="translationZ"`
`                android:valueTo="6dp"`
`                android:valueType="floatType"/>`
`        </set>`
`    </item>`
`</selector>`

On the normal CardView you don't have to specify the elevation when using this animator, but in this version you do, which means that the animator is doing nothing.

Any thoughts on how to add state lists to these?

Thanks.

**Comment by nvl2val** [comment]
@THEMrFill thanks for your feedback.

 The difference between this version and the official is that this version doesn't use post-lollipop version `CardView` implementation, which means `android:elevation` will not work on shadow. So `translationZ` in your xml will have no effect. 

However, you can replace `translationZ` with `cardElevation` property instead and `app:cardMaxElevation` **must** be added to `CardView`. Its xml may like this:

    <com.p.cardview.CardView
        android:layout_width="200dp"
        android:layout_height="150dp"
        android:layout_gravity="center"
        app:cardShadowStartColor="#7f00ff00"
        app:cardShadowEndColor="#0000ff00"
        android:clickable="true"
        app:cardMaxElevation="10dp"
        android:stateListAnimator="@animator/press_on_touch"
        />

I'll close this issue. Reopen if you have more questions.

**Comment by THEMrFill** [comment]
Thanks, after playing with the changes I've got it looking good now.
